/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-05-25 08:02:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta http-equiv=\"Content-Type\" charset=\"text/html; charset=UTF-8\">\r\n");
      out.write("		<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\"  rel=\"stylesheet\">\r\n");
      out.write("		<title>Insert title here</title>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("	<!--<h1>Hello Worlds desde HTML!</h1>-->\r\n");
      out.write("	");
      out.write(" \r\n");
      out.write("	\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-12\">\r\n");
      out.write("				<div class=\"container mt-5\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-6 offset-3 formulario\">\r\n");
      out.write("							<!-- Formulario -->\r\n");
      out.write("							<h2 class=\"text-center mb-2\">Formulario de Datos</h2>\r\n");
      out.write("							\r\n");
      out.write("								<img class=\"rounded mx-auto d-block img-thumbnail\" src=\"https://i.blogs.es/8d2420/650_1000_java/1366_2000.png\"  width=\"70\" alt=\"...\">\r\n");
      out.write("						\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("							<form action=\"SvUsuarios\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("								<div class=\"mb-3\">\r\n");
      out.write("									<label for=\"name\" class=\"form-label\">Nombre</label> \r\n");
      out.write("									<input type=\"text\" class=\"form-control\" id=\"nombre\" name=\"name\" required>\r\n");
      out.write("								</div>\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"mb-3\">\r\n");
      out.write("									<label for=\"apellido\" class=\"form-label\">Apellido</label> \r\n");
      out.write("									<input type=\"text\" class=\"form-control\" id=\"apellido\" name=\"apellido\" required>\r\n");
      out.write("								</div>\r\n");
      out.write("								\r\n");
      out.write("\r\n");
      out.write("								<div class=\"mb-3\">\r\n");
      out.write("									<label for=\"last-name\" class=\"form-label\">Lenguaje favorito</label> \r\n");
      out.write("									<select class=\"form-select\" name=\"lenguaje\">\r\n");
      out.write("										<option selected>Abrir este menú de selección</option>\r\n");
      out.write("										<option value=\"Java\">Java</option>\r\n");
      out.write("										<option value=\"Python\">Python</option>\r\n");
      out.write("										<option value=\"JavaScript\">JavaScript</option>\r\n");
      out.write("									</select>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							<!-- checkbox  -->\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"form-check\">\r\n");
      out.write("							  <input class=\"form-check-input\" type=\"checkbox\" name=\"intereses\" value=\"Inteligencia Artificial\" id=\"flexCheckDefault\" checked>\r\n");
      out.write("							  <label class=\"form-check-label\" for=\"flexCheckDefault\">\r\n");
      out.write("							   Inteligencia Artificial\r\n");
      out.write("							  </label>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"form-check\">\r\n");
      out.write("							  <input class=\"form-check-input\" type=\"checkbox\" name=\"intereses\" value=\"Desarrollo de Software\" id=\"flexCheckChecked\" >\r\n");
      out.write("							  <label class=\"form-check-label\" for=\"flexCheckChecked\">\r\n");
      out.write("							    Desarrollo de Software\r\n");
      out.write("							  </label>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"form-check\">\r\n");
      out.write("							  <input class=\"form-check-input\" type=\"checkbox\" name=\"intereses\" value=\"Clean Code\" id=\"flexCheckChecked\">\r\n");
      out.write("							  <label class=\"form-check-label\" for=\"flexCheckChecked\">\r\n");
      out.write("							    Clean Code\r\n");
      out.write("							  </label>\r\n");
      out.write("							</div>\r\n");
      out.write("								\r\n");
      out.write("							<!-- / checkbox  -->\r\n");
      out.write("\r\n");
      out.write("							<div class=\"mt-4 form-check\">\r\n");
      out.write("								<input class=\"form-check-input\" type=\"radio\" name=\"perfil\" value=\"FrontEnd\" id=\"flexRadioDefault1\"> \r\n");
      out.write("								<label class=\"form-check-label\" for=\"flexRadioDefault1\">FrontEnd</label>\r\n");
      out.write("							</div>\r\n");
      out.write("								\r\n");
      out.write("							<div class=\"form-check\">\r\n");
      out.write("								<input class=\"form-check-input\" type=\"radio\" name=\"perfil\" value=\"Backend\" id=\"flexRadioDefault1\"> \r\n");
      out.write("								<label class=\"form-check-label\" for=\"flexRadioDefault1\">Backend</label>\r\n");
      out.write("							</div>\r\n");
      out.write("								\r\n");
      out.write("							<div class=\"form-check mb-2\">\r\n");
      out.write("								<input class=\"form-check-input\" type=\"radio\" name=\"perfil\" value=\"FullStack\" id=\"flexRadioDefault2\" checked>\r\n");
      out.write("								<label class=\"form-check-label\" for=\"flexRadioDefault2\">FullStack</label>\r\n");
      out.write("							</div>\r\n");
      out.write("								\r\n");
      out.write("						\r\n");
      out.write("							<div class=\"d-grid gap-2 mt-4\">\r\n");
      out.write("								<button type=\"submit\" class=\"btn btn-primary\">Enviar</button>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-12\">\r\n");
      out.write("				<div class=\"container mt-2\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-6 offset-3\">\r\n");
      out.write("							<form action=\"SvUsuarios\" method=\"GET\">\r\n");
      out.write("								<div class=\"d-grid gap-2\">\r\n");
      out.write("									<button type=\"submit\" class=\"btn btn-success\">Mostrar Usuarios</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("						\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
